apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mautic 
  labels:
    app: mautic 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mautic 
  template:
    metadata:
      labels:
        app: mautic 
    spec:
      containers:
        - image: mautic/mautic 
          name: mautic
          env:
          - name: MAUTIC_DB_HOST
            value: mysql:3306
          - name: MAUTIC_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql
                key: password
          ports:
            - containerPort: 80
              name: mautic
